KUniversity/Areas/Instructor/Controllers/HTEClassesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KUniversity.Models;

namespace KUniversity.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    public class HTEClassesController : Controller
    {
        private Models.Instructor _instructor;
        private int adminDeptID = -1;
        private int htEClassID = -1;

        private readonly KUniversityContext _context;

        public HTEClassesController(KUniversityContext context)
        {
            _context = context;    
        }

        // GET: Instructor/HTEClasses
        public async Task<IActionResult> Index()
        {
            SetViewData();
            var classes = await _context.Eclass
                .Include(e => e.Instructor)
                .Include(e => e.Major)
                .Include(e => e.Student)
                .SingleOrDefaultAsync(e => e.Id == htEClassID);

            return View(classes);
        }

        // GET: Instructor/HTEClasses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            SetViewData();
            if (id == null)
            {
                return NotFound();
            }

            var eClass = await _context.Eclass
                .Include(e => e.Instructor)
                .Include(e => e.Major)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (eClass == null)
            {
                return NotFound();
            }

            return View(eClass);
        }

        // GET: Instructor/HTEClasses/Create
        public IActionResult Create()
        {
            SetViewData();
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name");
            ViewData["MajorID"] = new SelectList(_context.Major, "Id", "Title");
            return View();
        }

        // POST: Instructor/HTEClasses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,InstructorID,MajorID,StartYear,Order")] Eclass eClass)
        {
            SetViewData();
            if (ModelState.IsValid)
            {
                _context.Add(eClass);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name", eClass.InstructorId);
            ViewData["MajorID"] = new SelectList(_context.Major, "Id", "Title", eClass.MajorId);
            return View(eClass);
        }

        // GET: Instructor/HTEClasses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            SetViewData();
            if (id == null)
            {
                return NotFound();
            }

            var eClass = await _context.Eclass.SingleOrDefaultAsync(m => m.Id == id);
            if (eClass == null)
            {
                return NotFound();
            }
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name", eClass.InstructorId);
            ViewData["MajorID"] = new SelectList(_context.Major, "Id", "Title", eClass.MajorId);
            return View(eClass);
        }

        // POST: Instructor/HTEClasses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,InstructorID,MajorID,StartYear,Order")] Eclass eClass)
        {
            SetViewData();
            if (id != eClass.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(eClass);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EClassExists(eClass.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name", eClass.InstructorId);
            ViewData["MajorID"] = new SelectList(_context.Major, "Id", "Title", eClass.MajorId);
            return View(eClass);
        }

        // GET: Instructor/HTEClasses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            SetViewData();
            if (id == null)
            {
                return NotFound();
            }

            var eClass = await _context.Eclass
                .Include(e => e.Instructor)
                .Include(e => e.Major)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (eClass == null)
            {
                return NotFound();
            }

            return View(eClass);
        }

        // POST: Instructor/HTEClasses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            SetViewData();
            var eClass = await _context.Eclass.SingleOrDefaultAsync(m => m.Id == id);
            _context.Eclass.Remove(eClass);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool EClassExists(int id)
        {
            return _context.Eclass.Any(e => e.Id == id);
        }

        private void SetViewData()
        {
            SetAccount();
            ViewData["Gender"] = _instructor.Gender;
            ViewData["AccountName"] = _instructor.Name;

            adminDeptID = _context.Department.SingleOrDefault(d => d.InstructorId == _instructor.Id)?.Id ?? -1;

            ViewData["AdminDeptID"] = adminDeptID;

            if (adminDeptID != -1)
            {
                ViewData["Dept"] = _context.Department.SingleOrDefault(d => d.Id == adminDeptID);
            }

            htEClassID = _context.Eclass.FirstOrDefault(e => e.InstructorId == _instructor.Id)?.Id ?? -1;

            ViewData["HTEClassID"] = htEClassID;
        }

        private void SetAccount()
        {
            int id = Program.AccoutnID;
            //int id = HttpContext.Session.Get<int>("Account");
            _instructor = _context.Instructor.SingleOrDefault(i => i.Id == id);
            adminDeptID = -1;
            htEClassID = -1;
        }
    }
}

KUniversity/Areas/Instructor/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>@ViewData["Title"] - KUniversity</title>
  <link rel="shortcut icon" href="~/favicon.ico">

  <environment names="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/lib/mdl/iconfont/material-icons.css" />
    <link rel="stylesheet" href="~/lib/mdl/material.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
  </environment>
  <environment names="Staging,Production">
    <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
          asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
          asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    <link rel="stylesheet" href="~/lib/mdl/iconfont/material-icons.css" />
    <link rel="stylesheet" href="~/lib/mdl/material.min.css" />
    <link rel="stylesheet" href="~/css/site.min.css" />
  </environment>
</head>

@{
    var deptID = (int)ViewData["AdminDeptID"];
    var ecID = (int)ViewData["HTEClassID"];

    var isDeptAdmin = deptID != -1;
    var isHeadTeacher = ecID != -1;
}

<body>
  <div class="db-layout mdl-layout mdl-js-layout mdl-layout--fixed-drawer mdl-layout--fixed-header">

    <header class="db-header mdl-layout__header mdl-color--indigo-600">
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title">@ViewData["PageTtile"]</span>
        <div class="mdl-layout-spacer"></div>
        <a asp-area="" asp-action="Index" asp-controller="Home"
           class="mdl-button mdl-js-button mdl-color-text--white" id="logoutbtn">
          <i class="material-icons">exit_to_app</i>
        </a>
        <div class="mdl-tooltip" data-mdl-for="logoutbtn">安全退出</div>
      </div>
    </header>

    <div class="db-drawer mdl-layout__drawer mdl-color--indigo-500">
      <header class="db-drawer-header">
        @if ((int)ViewData["Gender"] == 0)
        {
            <img src="~/images/Avatar/avatar_female.png" class="db-avatar">
        }
        else
        {
            <img src="~/images/Avatar/avatar_male.png" class="db-avatar">
        }

        <div class="db-drawer-header-name">
          <span>@ViewData["AccountName"]</span>
        </div>
      </header>

      <nav class="db-navigation mdl-navigation mdl-color--indigo-600">
        <a asp-action="Index" asp-controller="InstructorHome" asp-area="Instructor"
           class="mdl-navigation__link">
          <i class="material-icons">dashboard</i>概览
        </a>
        <a asp-action="Course" asp-controller="InstructorHome" asp-area="Instructor"
           class="mdl-navigation__link">
          <i class="material-icons">library_books</i>课程
        </a>
        <a asp-action="Profile" asp-controller="InstructorHome" asp-area="Instructor"
           class="mdl-navigation__link">
          <i class="material-icons">account_box</i>个人信息
        </a>
        @if (isHeadTeacher)
        {
            <a asp-action="Index" asp-controller="HTEClasses" 
               asp-area="Instructor" class="mdl-navigation__link">
              <i class="material-icons">group</i>行政班
            </a>
        }
        @if (isDeptAdmin)
        {
            <a asp-action="Index" asp-controller="DepartmentMajors" 
               asp-area="Instructor" class="mdl-navigation__link">
              <i class="material-icons">donut_small</i>学院专业管理
            </a>
            <a asp-action="Index" asp-controller="DepartmentCourses"
               asp-area="Instructor" class="mdl-navigation__link">
              <i class="material-icons">chrome_reader_mode</i>学院课程管理
            </a>
        }
        <div class="mdl-layout-spacer"></div>
        <div class="db-drawer-header-name" style="margin-bottom: 20px;">
          <span>&copy; @DateTime.Now.Year - KUniversity</span>
        </div>
      </nav>
    </div>
    <main class="mdl-layout__content mdl-color--grey-100">
      <div class="mdl-grid db-content">
        @RenderBody()
      </div>
    </main>
  </div>

  <environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/mdl/material.min.js"></script>
  </environment>
  <environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
    </script>
    <script src="~/lib/mdl/material.min.js"></script>
  </environment>

  @RenderSection("scripts", required: false)
</body>

</html>