KUniversity/Models/Course.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace KUniversity.Models
{
    public partial class Course
    {
        public Course()
        {
            Courseassignment = new HashSet<Courseassignment>();
        }

        public int Id { get; set; }
        public int DepartmentId { get; set; }

        [Required(ErrorMessage = "该项不可为空")]
        [Display(Name = "课程名称")]
        public string Title { get; set; }

        public virtual ICollection<Courseassignment> Courseassignment { get; set; }

        [Display(Name = "所在学院")]
        public virtual Department Department { get; set; }
    }
}

KUniversity/Areas/Instructor/Controllers/InstructorHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using KUniversity.Models;
using Microsoft.EntityFrameworkCore;

namespace KUniversity.Areas.Instructor.Controllers
{
    [Area("Instructor")]
    public class InstructorHomeController : Controller
    {
        private Models.Instructor _instructor;
        private int adminDeptID = -1;
        private int htEClassID = -1;

        private readonly KUniversityContext _context;

        public InstructorHomeController(KUniversityContext context)
        {
            _context = context;
        }

        [ActionName("Index")]
        public async Task<IActionResult> IndexAsync()
        {
            SetViewData();

            var ins = await _context.Instructor
                .Where(i => i.Id == _instructor.Id)
                .Include(i => i.Courseassignment)
                    .ThenInclude(ca => ca.Course)
                        .ThenInclude(c => c.Department)
                            .ThenInclude(d => d.Campus)
                .AsNoTracking()
                .FirstAsync();

            return View(ins);
        }

        [ActionName("Profile")]
        public async Task<IActionResult> ProfileAsync()
        {
            SetViewData();

            var ins = await _context.Instructor
                .Where(i => i.Id == _instructor.Id)
                .Include(i => i.Courseassignment)
                    .ThenInclude(ca => ca.Course)
                        .ThenInclude(c => c.Department)
                            .ThenInclude(d => d.Campus)
                .AsNoTracking()
                .FirstAsync();

            return View(ins);
        }

        [ActionName("Course")]
        public async Task<IActionResult> CourseAsync()
        {
            SetViewData();

            var ins = await _context.Instructor
                .Where(i => i.Id == _instructor.Id)
                .Include(i => i.Courseassignment)
                    .ThenInclude(ca => ca.Course)
                        .ThenInclude(c => c.Department)
                            .ThenInclude(d => d.Campus)
                .AsNoTracking()
                .FirstAsync();

            return View(ins);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DepartmentId,Name,Gender,Nation,HireDate,PhoneNumber,Email,Academic,OfficeLocation,Password")] Models.Instructor instructor)
        {
            if (id != instructor.Id)
            {
                return NotFound();
            }
            
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(instructor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!InstructorExists(instructor.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Profile");
            }
            return RedirectToAction("Profile");
        }

        [ActionName("CourseScore")]
        public async Task<IActionResult> CourseScoreAsync(int? id)
        {
            SetViewData();

            var ens = await _context.Enrollment
                .Where(e => e.CourseAssignmentId == id)
                .Where(e => e.CourseAssignment.InstructorId == _instructor.Id)
                .Include(e => e.CourseAssignment)
                    .ThenInclude(ca => ca.Course)
                        .ThenInclude(c => c.Department)
                            .ThenInclude(d => d.Campus)
                .Include(e => e.CourseAssignment)
                    .ThenInclude(ca => ca.Instructor)
                .Include(e => e.Student)
                    .ThenInclude(s => s.Eclass)
                        .ThenInclude(ec => ec.Major)
                .AsNoTracking()
                .ToListAsync();

            if (ens == null || ens.Count() < 1)
            {
                return Content($"{_instructor.Id}");
            }

            return View(ens);
        }

        private void SetViewData()
        {
            SetAccount();
            ViewData["Gender"] = _instructor.Gender;
            ViewData["AccountName"] = _instructor.Name;

            adminDeptID = _context.Department.SingleOrDefault(d => d.InstructorId == _instructor.Id)?.Id ?? -1;

            ViewData["AdminDeptID"] = adminDeptID;

            htEClassID = _context.Eclass.FirstOrDefault(e => e.InstructorId == _instructor.Id)?.Id ?? -1;

            ViewData["HTEClassID"] = htEClassID;
        }

        private void SetAccount()
        {
            int id = Program.AccoutnID;
            //int id = HttpContext.Session.Get<int>("Account");
            _instructor = _context.Instructor.SingleOrDefault(i => i.Id == id);
            adminDeptID = -1;
            htEClassID = -1;
        }

        private bool InstructorExists(int id)
        {
            return _context.Instructor.Any(e => e.Id == id);
        }
    }
}

KUniversity/Areas/Instructor/Views/InstructorHome/Course.cshtml
@model KUniversity.Models.Instructor

@{
    ViewData["Title"] = "课程";
    ViewData["PageTtile"] = "所有课程";

    var courses = Model.Courseassignment;
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-grid" style="width: 100%;">
  <div style="width: 100%; margin-top: 40px">
    <span style="font-size: 18px">共有 @courses.Count() 门课</span>
  </div>
  <hr style="width: 100%" />

  @for (int i = 1; i < 6; i++)
  {
      <div class="mdl-grid" style="width: 100%; margin-bottom: 30px;">
        @{
            var cses = courses.Where(c => c.ClassTimeInDayOfWeek((DayOfWeek)i));
            if (cses.Count() > 0)
            {
                <div style="width: 100%">
                  <div class="mdl-chip" style="font-size: 18px; margin-bottom: 20px; width: 60px;">
                    <span class="mdl-chip__text" style="text-align: center; width: 100%;"> 周 @i</span>
                  </div>
                </div>
              foreach (var item in courses.Where(c => c.ClassTimeInDayOfWeek((DayOfWeek)i)))
              {
                <div class="mdl-cell mdl-cell--4-col mdl-shadow--2dp"
                     style="background-color: white">
                  <div class="mdl-card__title">
                    <a asp-action="CourseScore" asp-controller="InstructorHome" 
                       asp-area="Instructor" asp-route-id="@item.Id"
                       class="mdl-button mdl-button--primary">
                      <span class="mdl-card__title-text">@item.Course.Title</span>
                    </a>
                  </div>
                  @{ var timeLocation = item.ClassTimeLocation((DayOfWeek)i); }
                  <div class="mdl-card__supporting-text">
                    <span style="float: left; margin-left: 15px">#@item.Course.Id</span>
                    <span style="float: right">
                      @timeLocation.Time 节 | 于 @timeLocation.Location | @item.Course.Department.Campus.Name
                    </span>
                  </div>
                </div>
               }
             }
        }
      </div>
}
</div>

KUniversity/Areas/Instructor/Views/InstructorHome/CourseScore.cshtml
@model List<Enrollment>

@{
    ViewData["Title"] = "概览";
    var ca = Model[0].CourseAssignment;
    var course = ca.Course;
    var code = course.Department.Campus.Code + ca.OrderText;
    ViewData["PageTtile"] = course.Title;
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-grid" style="width: 100%;">

  <div style="width: 100%; margin-top: 40px">
    <span style="font-size: 16px">#@course.Id &nbsp;&nbsp; @@ @code</span>
    <span style="font-size: 16px; float: right">共 @Model.Count() 名学生</span>
  </div>
  <hr style="width: 100%" />


  <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp"
         style="width: 100%">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">学号</th>
        <th class="mdl-data-table__cell--non-numeric">姓名</th>
        <th class="mdl-data-table__cell--non-numeric">专业</th>
        <th>成绩</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model)
      {
          <tr>
            <td class="mdl-data-table__cell--non-numeric">
              @Html.DisplayFor(modelItem => item.Student.Id)
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              @Html.DisplayFor(modelItem => item.Student.Name)
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              @Html.DisplayFor(modelItem => item.Student.Eclass.Major.Title)
            </td>
            <td>
              @Html.DisplayFor(modelItem => item.Grade)
            </td>
          </tr>
      }
    </tbody>
  </table>
</div>

KUniversity/Areas/Instructor/Views/InstructorHome/Index.cshtml
@model KUniversity.Models.Instructor

@{
    ViewData["Title"] = "概览";
    ViewData["PageTtile"] = "概览";

    var today = DateTime.Now.DayOfWeek;
    var todayCourses = Model.Courseassignment.Where(c => c.ClassTimeInDayOfWeek(today));
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-grid" style="width: 100%;">
  <div style="width: 100%; margin-top: 40px">
    <span style="font-size: 18px">@DateTime.Now.ToString("yyyy-MM-dd") 今日课程</span>
    <span style="float: right">共 @todayCourses.Count() 门课</span>
  </div>
  <hr style="width: 100%" />

  @{
      if (todayCourses.Count() < 1)
      {
          <div class="mdl-grid">
            无
          </div>
      }
      else
      {
        foreach (var item in todayCourses)
        {
              <div class="mdl-cell mdl-cell--4-col mdl-shadow--2dp"
                   style="background-color: white">
                <div class="mdl-card__title">
                  <a asp-action="CourseScore" asp-controller="InstructorHome" 
                     asp-area="Instructor" asp-route-id="@item.Id"
                     class="mdl-button mdl-button--primary">
                    <span class="mdl-card__title-text">@item.Course.Title</span>
                  </a>
                </div>
                @{ var timeLocation = item.ClassTimeLocation(today); }
                <div class="mdl-card__supporting-text">
                  <span style="float: left; margin-left: 15px">#@item.Course.Id</span>
                  <span style="float: right">
                    @timeLocation.Time 节 | 于 @timeLocation.Location | @item.Course.Department.Campus.Name
                  </span>
                </div>
              </div>
        }
      }
  }

</div>

KUniversity/Areas/Instructor/Views/InstructorHome/Profile.cshtml
@model Instructor

@{
    ViewData["Title"] = "个人信息";
    ViewData["PageTtile"] = "个人信息";
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-grid" style="width: 100%;">
  <form asp-action="Edit" asp-controller="InstructorHome" class="mdl-grid">
    <div class="modal-dialog">
      <div class="modal-content" style="padding-top: 20px;">
        <div class="modal-body">
          <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="DepartmentId" class="form-control" type="hidden" />
            @*<input asp-for="ID" class="form-control" type="hidden" />*@
            <input asp-for="Gender" class="form-control" type="hidden" />
            <div class="form-group">
              <label asp-for="Id" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
              </div>
            </div>
            <div class="form-group">
              <label asp-for="Name" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
              </div>
            </div>
            @*<div class="form-group">
              <label asp-for="Gender" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Gender" class="form-control" readonly />
                <span asp-validation-for="Gender" class="text-danger"></span>
              </div>
            </div>*@
            <div class="form-group">
              <label asp-for="Nation" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Nation" class="form-control" />
                <span asp-validation-for="Nation" class="text-danger"></span>
              </div>
            </div>
            <div class="form-group">
              <label asp-for="HireDate" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="HireDate" class="form-control" readonly />
                <span asp-validation-for="HireDate" class="text-danger"></span>
              </div>
            </div>
            <div class="form-group">
              <label asp-for="PhoneNumber" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
              </div>
            </div>
            <div class="form-group">
              <label asp-for="Email" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
              </div>
            </div>
            <div class="form-group">
              <label asp-for="Academic" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Academic" class="form-control" />
                <span asp-validation-for="Academic" class="text-danger"></span>
              </div>
            </div>
            <div class="form-group">
              <label asp-for="OfficeLocation" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="OfficeLocation" class="form-control" />
                <span asp-validation-for="OfficeLocation" class="text-danger"></span>
              </div>
            </div>
            <div class="form-group">
              <label asp-for="Password" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <a asp-action="Index" class="mdl-button mdl-button--accent"
                  style="float: left; position:relative; left: 12px; line-height: 36px;">
            取消
          </a>
          <input type="submit" value="保存"
                 class="mdl-button mdl-button--colored" />
        </div>
      </div>
    </div>
  </form>
</div>


@Html.Partial("_ValidationScriptsPartial")