KUniversity/Areas/Admin/Controllers/CampusMgrController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KUniversity.Models;
using KUniversity.Models.ViewModels;

namespace KUniversity.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CampusMgrController : Controller
    {
        private readonly KUniversityContext _context;

        public CampusMgrController(KUniversityContext context)
        {
            _context = context;
        }

        // GET: Admin/CampusMgr
        public IActionResult Index()
        {
            var vm = new AdminIndexData()
            {
                Campuses = _context.Campus.Include(c => c.Department),
                Departments = _context.Department.Include(d => d.Major)
            };
            return View(vm);
        }

        // GET: Admin/CampusMgr/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var campus = await _context.Campus
                .SingleOrDefaultAsync(m => m.Id == id);
            if (campus == null)
            {
                return NotFound();
            }

            var data = new CampusDetailsData
            {
                Campus = campus,
                Departments = _context.Department.Where(d => d.CampusId == campus.Id).Include(d => d.Instructor)
            };

            return View(data);
        }

        // GET: Admin/CampusMgr/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/CampusMgr/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Address")] Campus campus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(campus);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(campus);
        }

        // GET: Admin/CampusMgr/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var campus = await _context.Campus.SingleOrDefaultAsync(m => m.Id == id);
            if (campus == null)
            {
                return NotFound();
            }
            return View(campus);
        }

        // POST: Admin/CampusMgr/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Address")] Campus campus)
        {
            if (id != campus.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(campus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CampusExists(campus.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(campus);
        }

        // GET: Admin/CampusMgr/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var campus = await _context.Campus.Include(c => c.Department)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (campus == null)
            {
                return NotFound();
            }

            return View(campus);
        }

        // POST: Admin/CampusMgr/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var campus = await _context.Campus.SingleOrDefaultAsync(m => m.Id == id);
            _context.Campus.Remove(campus);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool CampusExists(int id)
        {
            return _context.Campus.Any(e => e.Id == id);
        }
    }
}

KUniversity/Areas/Admin/Controllers/DepartmentMgrController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KUniversity.Models;

namespace KUniversity.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class DepartmentMgrController : Controller
    {
        private readonly KUniversityContext _context;

        public DepartmentMgrController(KUniversityContext context)
        {
            _context = context;    
        }

        // GET: Admin/DepartmentMgr
        public async Task<IActionResult> Index()
        {
            var kUniversityContext = _context.Department.Include(d => d.Instructor).Include(d => d.Campus);
            return View(await kUniversityContext.ToListAsync());
        }

        // GET: Admin/DepartmentMgr/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .Include(d => d.Instructor)
                .Include(d => d.Campus)
                .Include(d => d.Major)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Admin/DepartmentMgr/Create
        public IActionResult Create()
        {
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name");
            ViewData["CampusID"] = new SelectList(_context.Campus, "Id", "Name");
            return View();
        }

        // POST: Admin/DepartmentMgr/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CampusId,InstructorId,Name,StartTime")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name", department.InstructorId);
            ViewData["CampusID"] = new SelectList(_context.Campus, "Id", "Name", department.CampusId);
            return View(department);
        }

        // GET: Admin/DepartmentMgr/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department.SingleOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name", department.InstructorId);
            ViewData["CampusID"] = new SelectList(_context.Campus, "Id", "Name", department.CampusId);
            return View(department);
        }

        // POST: Admin/DepartmentMgr/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CampusId,InstructorId,Name,StartTime")] Department department)
        {
            if (id != department.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            ViewData["InstructorID"] = new SelectList(_context.Instructor, "Id", "Name", department.InstructorId);
            ViewData["CampusID"] = new SelectList(_context.Campus, "Id", "Name", department.CampusId);
            return View(department);
        }

        // GET: Admin/DepartmentMgr/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var department = await _context.Department
                .Include(d => d.Instructor)
                .Include(d => d.Campus)
                .Include(d => d.Major)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Admin/DepartmentMgr/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var department = await _context.Department.SingleOrDefaultAsync(m => m.Id == id);
            _context.Department.Remove(department);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool DepartmentExists(int id)
        {
            return _context.Department.Any(e => e.Id == id);
        }
    }
}

KUniversity/Areas/Admin/Views/CampusMgr/Create.cshtml
@model Campus

@{
    ViewData["Title"] = "新增校区";
    ViewData["PageTtile"] = "新增校区";
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-grid">
  <form asp-action="Create">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">新增校区</h5>
        </div>

        <div class="modal-body">
          <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
              <label asp-for="Name" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
              </div>
            </div>

            <div class="form-group">
              <label asp-for="Address" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <a asp-action="Index" class="mdl-button mdl-button--accent"
                  style="float: left; position:relative; left: 12px; line-height: 36px;">取消</a>
          <input type="submit" value="新增"
                 class="mdl-button mdl-button--colored" />
        </div>
      </div>
    </div>
  </form>
</div>

@Html.Partial("_ValidationScriptsPartial");

KUniversity/Areas/Admin/Views/CampusMgr/Delete.cshtml
@model Campus

@{
    ViewData["Title"] = "删除校区";
    ViewData["PageTtile"] = "确认删除";
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-card mdl-shadow--2dp mdl-grid" style="width: 60%; padding: 10px 20px">
  <h5>确认删除该校区？</h5>
  <hr />
  <input type="hidden" asp-for="Id" />
  <div class="dl-horizontal" style="width: 100%; text-align: center">    
    <p style="font-size: 22px">
      @Html.DisplayFor(model => model.Name)
    </p>
    <p>
      @Html.DisplayFor(model => model.Address)
    </p>
    <span style="font-size: 14px">
      包含 @Model.Department.Count() 个学院
    </span>
  </div>

  <form asp-action="Delete" class="mdl-grid" style="display: block; width: 100%;">
    <div class="form-actions no-color">
      <button type="submit" style="float: right;" id="deleteConfirm"
              class="mdl-button mdl-button--accent mdl-button--fab mdl-js-button mdl-js-ripple-effect">
        <i class="material-icons">delete</i>
      </button>
      <a asp-action="Index"
         class="mdl-button mdl-button--primary">
        取消
      </a>
    </div>
  </form>
</div>

<div class="mdl-tooltip" for="deleteConfirm">确认删除</div>

KUniversity/Areas/Admin/Views/CampusMgr/Details.cshtml
@model CampusDetailsData

@{
    ViewData["Title"] = Model.Campus.Name + "校区";
    ViewData["PageTtile"] = Model.Campus.Name + "校区";
}

<style>
  #back {
    position: absolute;
    left: 3%;
  }

  a:hover {
    text-decoration: none;
  }
</style>

<a asp-action="Index" id="back"
   style="float: right;"
   class="mdl-button mdl-button--primary mdl-button--fab mdl-js-button mdl-js-ripple-effect">
  <i class="material-icons">arrow_back</i>
</a>

<div class="mdl-card mdl-shadow--2dp mdl-grid" style="width: 60%; padding: 10px 20px">
  <div style="width: 100%; padding-top: 20px">
    <h5 style="font-size: 20px;">
      @Model.Campus.Name 校区
    </h5>
    <span style="font-size: 14px;">
      @Model.Campus.Address
    </span>
  </div>

  <div style="width: 100%; height: 36px;">
    <hr />
    <div style="float: right; padding: 10px; margin-top: -56px">
      <a asp-action="Edit" asp-controller="CampusMgr" asp-route-id="@Model.Campus.Id" id="editc"
         class="mdl-button mdl-button--primary mdl-button--fab mdl-js-button mdl-js-ripple-effect">
        <i class="material-icons">edit</i>
      </a>
    </div>
  </div>
</div>

<div class="mdl-tooltip" for="back">返回</div>
<div class="mdl-tooltip" for="editc">编辑</div>

<div class="mdl-grid" style="width: 100%; margin-bottom: 40px">

  <p style="font-size: 16px; margin-bottom: -5px; margin-top: 15px;">包含 @Model.Departments.Count() 个学院</p>
  <hr />

  <table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp"
         style="width: 100%">
    <thead>
      <tr>
        <th class="mdl-data-table__cell--non-numeric">学院名称</th>
        <th class="mdl-data-table__cell--non-numeric">建立时间</th>
        <th class="mdl-data-table__cell--non-numeric">学院管理员</th>
      </tr>
    </thead>
    <tbody>
      @foreach (var item in Model.Departments)
      {
          <tr>
            <td class="mdl-data-table__cell--non-numeric">
              <a asp-action="Details" asp-controller="DepartmentMgr" asp-route-id="@item.Id"
                 class="mdl-button mdl-button--primary">
                @Html.DisplayFor(modelItem => item.Name)
              </a>
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              @Html.DisplayFor(modelItem => item.StartTime)
            </td>
            <td class="mdl-data-table__cell--non-numeric">
              @Html.DisplayFor(modelItem => item.Instructor.Name)
            </td>
          </tr>
      }
    </tbody>
  </table>

</div>

KUniversity/Areas/Admin/Views/CampusMgr/Edit.cshtml
@model Campus

@{
    ViewData["Title"] = "编辑校区";
    ViewData["PageTtile"] = "编辑校区";
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-grid">
  <form asp-action="Edit">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">编辑校区</h5>
        </div>

        <div class="modal-body">
          <div class="form-horizontal">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
              <label asp-for="Name" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
              </div>
            </div>

            <div class="form-group">
              <label asp-for="Address" class="col-md-2 control-label"></label>
              <div class="col-md-10">
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
              </div>
            </div>
          </div>
        </div>

        <div class="modal-footer">
          <a asp-action="Index" class="mdl-button mdl-button--accent"
                  style="float: left; position:relative; left: 12px; line-height: 36px;">取消</a>
          <input type="submit" value="保存"
                 class="mdl-button mdl-button--colored" />
        </div>
      </div>
    </div>
  </form>
</div>

@Html.Partial("_ValidationScriptsPartial");

KUniversity/Areas/Admin/Views/CampusMgr/Index.cshtml
@model AdminIndexData

@{
    ViewData["Title"] = "校区管理";
    ViewData["PageTtile"] = "校区管理";
}

<style>
  a:hover {
    text-decoration: none;
  }
</style>

<div class="mdl-grid" style="width: 100%">
  @foreach (var item in Model.Campuses)
  {
      <div class="mdl-cell mdl-cell--4-col mdl-card mdl-shadow--2dp">
        <div class="mdl-card__title mdl-card--expand">
          <a asp-action="Details" asp-controller="CampusMgr" asp-route-id="@item.Id"
             class="campusEntry mdl-button mdl-button--colored">
            <h2 class="mdl-card__title-text">@item.Name 校区</h2>
          </a>
        </div>

        <div class="mdl-card__supporting-text">
          @item.Address
        </div>

        <div class="mdl-card__actions mdl-card--border">
          <span style="line-height: 36px; position:relative; left:8px; font-size:12px;">
            共 @item.Department.Count() 个学院
          </span>
          <a asp-action="Edit" asp-controller="CampusMgr" asp-route-id="@item.Id"
             class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
             data-toggle="tooltip" data-placement="top" title="编辑"
             style="float: right;">
            <i class="material-icons">edit</i>
          </a>
          <a asp-action="Delete" asp-controller="CampusMgr" asp-route-id="@item.Id"
             class="mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect"
             data-toggle="tooltip" data-placement="top" title="删除"
             style="float: right">
            <i class="material-icons">delete</i>
          </a>
        </div>
      </div>
  }
</div>

<a asp-action="Create" id="createCampus"
   class="mdl-button mdl-button--colored mdl-button--fab mdl-js-button mdl-js-ripple-effect"
   style="position:fixed; bottom: 60px; right: 120px;">
  <i class="material-icons">add</i>
</a>
<div class="mdl-tooltip" for="createCampus">新增校区</div>

@Html.Partial("_BSTollTipPartial")